### ISSUE TITLE
Vacuity-guided correct evidence regularization

### ISSUE THREAD

**Issue by MissingJoe** [pandeydeep9/EvidentialResearch2023#1]
Hello, your work on evidential deep learning is fantastic. After I read your code in utilFiles/losses.py, the vacuity-guided correct evidence regularization term is not same as the term appeared in the paper.
Your implementation in this repo:
```python
if args.use_vac_reg:
        output_correct = output*target
        loss -= torch.sum(vacuity * output_correct)/output_correct.shape[0]
```
In the paper, the regularization term seems implemented by
```python
if args.use_vac_reg:
        output_correct = torch.log(get_evidence(output))*target
        loss -= torch.sum(vacuity * output_correct)/output_correct.shape[0]
```
So I am wondering about how to solve this problem. Is my understanding of the code or the paper wrong?

**Comment by pandeydeep9** [comment]
I used an implementation trick for the code implementation. 

I use the exponential activation function
For the exponential activation function, the evidence is obtained as 
  evidence_output = get_evidence(output) = torch.exp(output)
and torch.log (get_evidence(output)) = torch.log(torch.exp(output)) = output.

So, both the implementations are correct and mathematically equivalent.

Hope this helps. 
Best,
Deep

**Comment by MissingJoe** [comment]
Thanks for your reply, my problem is solved.
